try{
  const result = (await ticketService.cancel(id)).data;
} catch (error) {
  console.log(error);
}